import sys
list1 = [1,2,'gtm']
print(sys.getsizeof(list1))
list1.append("name")
print("2 items-",sys.getsizeof(list1))
list1.append(10)
print("3 items-",sys.getsizeof(list1))
list1.append(20)
print("4 items-",sys.getsizeof(list1))
list1.append(30)
print("5 items-",sys.getsizeof(list1))
list1.append(50)
print("6 items-",sys.getsizeof(list1))
list1.append(60)
print("7 items-",sys.getsizeof(list1))
list1.append("gautam")
print("8 items-",sys.getsizeof(list1))
list1.append("ptl")
print("9 items-",sys.getsizeof(list1))
list1.append(100)
print("10 items-",sys.getsizeof(list1))
list1.append(101)
print("11 items-",sys.getsizeof(list1))
list1.append(102)
print("12 items-",sys.getsizeof(list1))
list1.append(103)
print("13 items-",sys.getsizeof(list1))
list1.append(104)
print("14 items-",sys.getsizeof(list1))
list1.append(105)
print("15 items-",sys.getsizeof(list1))
list1.append(106)
print("16 items-",sys.getsizeof(list1))
list1.append(45)
print("17 items-",sys.getsizeof(list1))
list1.append("happy")
print("18 items-",sys.getsizeof(list1))