INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('1', 'ID0001', 'IDU EXV', '0', '480', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('2', 'ID0002', 'Tliq', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('3', 'ID0003', 'Tgas', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('4', 'ID0004', 'Room Temp', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('5', 'ID0005', 'Supply Temp', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('6', 'ID0006', 'DCL', '0', '101', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('7', 'ID0007', 'IDU Capacity', '0.5', 'Free', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('8', 'ID0008', 'IDU Fan Step', '0-OFF', '5-Hi', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('9', 'ID0009', 'IDU Swing Position', '0- OFF', '1- Swing', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('10', 'ID0010', 'Set Temp.', '16', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('11', 'ID0011', 'Fire Input', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('12', 'ID0012', 'Door Input', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('13', 'ID0013', 'Shift Temp.', '0', '10', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('14', 'ID0014', 'Flaot Switch', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('15', 'ID0015', 'Drain Pump', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('16', 'ID0016', 'Drain Time Extension', '0', '900 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('17', 'ID0017', 'Drain ON Delay Time', '0', '900 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('18', 'ID0018', 'Tliq for Drain Pump', '0', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('19', 'ID0019', 'DC pump low rpm', '0', '500', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('20', 'ID0020', 'DC pump low rpm time', '0', '600 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('21', 'ID0021', 'IDU Fan Stop Time', '0', '180 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('22', 'ID0022', 'IDU Fan Startup Time at Hi', '0', '180 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('23', 'ID0023', 'Fan Feedback Time', '0', '180 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('24', 'ID0024', 'Max Time Fan in Draft', '0', '600 sec', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('25', 'ID0025', 'Tliq Temp H1 for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('26', 'ID0026', 'Tliq Temp H2 for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('27', 'ID0027', 'Tliq Temp H3 for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('28', 'ID0028', 'Tliq Temp H4 for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('29', 'ID0029', 'Tliq Temp H5 for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('30', 'ID0030', 'Tliq Temp for Fan', '-30', '105', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('31', 'ID0031', 'Time of Fan at Lo', '0', '300', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('32', 'ID0032', 'ΔT Lo Cool for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('33', 'ID0033', 'ΔT Me Cool for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('34', 'ID0034', 'ΔT Hi Cool for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('35', 'ID0035', 'ΔT Lo Heat for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('36', 'ID0036', 'ΔT Me Heat for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('37', 'ID0037', 'ΔT Hi Heat for Auto Fan', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('38', 'ID0038', 'Tliq for DCL 0', '0', '10', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('39', 'ID0039', 'Sleep Mode', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('40', 'ID0040', 'Sleep Mode Run Time', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('41', 'ID0041', 'Sleep Mode Time C1', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('42', 'ID0042', 'Sleep Mode Time C2', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('43', 'ID0043', 'Sleep Mode Time C3', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('44', 'ID0044', 'Sleep Mode Time C4', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('45', 'ID0045', 'Sleep Mode Set Temp C1', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('46', 'ID0046', 'Sleep Mode Set Temp C2', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('47', 'ID0047', 'Sleep Mode Set Temp C3', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('48', 'ID0048', 'Sleep Mode Set Temp C4', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('49', 'ID0049', 'Sleep Mode Set Temp H1', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('50', 'ID0050', 'Sleep Mode Set Temp H2', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('51', 'ID0051', 'Sleep Mode Set Temp H3', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('52', 'ID0052', 'Sleep Mode Set Temp H4', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('53', 'ID0053', 'Sleep Mode Time H1', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('54', 'ID0054', 'Sleep Mode Time H2', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('55', 'ID0055', 'Sleep Mode Time H3', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('56', 'ID0056', 'Sleep Mode Time H4', '0', '24', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('57', 'ID0057', 'Fan Time at Door Open', '0', '60', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('58', 'ID0058', 'Fan Speed at Door Open', '0-OFF', '5-Hi', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('59', 'ID0059', 'EXV Close in IT', '-520', '480', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('60', 'ID0060', 'EXV Open in IT', '0', '480', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('61', 'ID0061', 'Flap Position F5', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('62', 'ID0062', 'Flap Position F4', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('63', 'ID0063', 'Flap Position F3', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('64', 'ID0064', 'Flap Position F2', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('65', 'ID0065', 'Flap Position F1', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('66', 'ID0066', 'Flap Position F0', '0', '90', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('67', 'ID0067', 'Flap Time Before Close', '0', '300', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('68', 'ID0068', 'Motion Detection', '0-OFF', '1-ON', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('69', 'ID0069', 'Motion Detection Time', '0', '30', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('70', 'ID0070', 'Motion Sensor Timer', '0', '60', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('71', 'ID0071', 'Motion temp A in Cool', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('72', 'ID0072', 'Motion temp A in Heat', '-5', '5', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('73', 'ID0073', 'Motion temp B in Cool', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('74', 'ID0074', 'Motion temp B in Heat', '0', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('75', 'ID0075', 'Filter Clean Hrs', '0', '10000', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('76', 'ID0076', 'Filter Clean Fan Time', '0', '100 min', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('77', 'ID0077', 'EXV Open Bypass 1', '-520', '480', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('78', 'ID0078', 'EXV Open Bypass 2', '-520', '480', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('79', 'ID0079', 'EXV Time Bypass 2', '0', '100 min', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('80', 'ID0080', 'EXV Interval Bypass 2', '0', '100 min', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('81', 'ID0081', 'Fan Speed Bypass 2', 'LL', 'Hi', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('82', 'ID0082', 'Buzzer Time', '100', '5000', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('83', 'ID0083', 'Buzzer Time for OFF', '100', '5000', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('84', 'ID0084', 'Hotel Door Key Cool', '16', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('85', 'ID0085', 'Hotel Door Key Heat', '16', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('86', 'ID0086', 'Hotel Door Key Fan', 'LL', 'Hi', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('87', 'ID0087', 'Standby IDU Temp Limit', '16', '32', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('88', 'ID0088', 'TFA & HRV ΔT Cool', '-20', '0', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('89', 'ID0089', 'TFA & HRV ΔT Heat', '20', '0', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('90', 'ID0090', 'DI 1 (The digital input selected for DI 1)', '-', '-', 'nan', 'idu');
INSERT INTO Sheet1-IDU (id, parameterId, parameterName, minRange, maxRange, categoryId, unit) VALUES ('91', 'ID0091', 'DI 2 (The digital input selected for DI 2)', '-', '-', 'nan', 'idu');
